import { useState, useCallback } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// Assets
import logo from "../public/images/logo.svg";

// Components
import { IconHome, IconPlus, IconPaper } from "../components/Icons";
import MenuItem from "../components/Menu/MenuItem";
import UserMenu from "~/components/Menu/UserMenu";
import { Menu, MenuItems } from "~/components/Menu/styles";
import { Container, WelcomeContainer, Welcome } from "~/components/Main/styles";
import { Card } from "~/components/Card/styles";
import Button from "~/components/Button";
import IconAdd from "~/components/Icons/IconAdd";

export interface IMenuItem {
  title: string;
  icon: JSX.Element;
}

export default function Home() {
  const menuItems: IMenuItem[] = [
    {
      title: "Home",
      icon: <IconHome />,
    },
    {
      title: "Pontuar",
      icon: <IconPlus />,
    },
    {
      title: "Regras",
      icon: <IconPaper />,
    },
  ];

  const [currentMenu, setCurrentMenu] = useState<string>("home");

  const handleEmitAlert = useCallback(() => {
    alert("Hello World!");
  }, []);

  return (
    <div className={styles.bg}>
      <Head>
        <title>CMS • Diamond</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu>
          <Image
            className={styles.logo}
            src={logo}
            alt="Logo"
            width={32}
            height={32}
            draggable={false}
          />

          <MenuItems>
            {menuItems.map((item: IMenuItem) => (
              <MenuItem
                key={item.title}
                icon={item.icon}
                title={item.title}
                isActive={item.title.toLowerCase() == currentMenu}
                onClick={() => setCurrentMenu(item.title.toLowerCase())}
              />
            ))}
          </MenuItems>

          <UserMenu />
        </Menu>

        <Container>
          <WelcomeContainer>
            <Welcome>Bem-vindo, Hendiw!</Welcome>
            <Button onClick={handleEmitAlert}>
              <IconAdd />
              PONTUAR
            </Button>
          </WelcomeContainer>
          <Card>Olá Mundo!</Card>
        </Container>
      </main>
    </div>
  );
}
