import Head from "next/head";
import Image from "next/image";
import styles from "~/styles/Home.module.css";

// Components
import { IconHome, IconPlus, IconPaper } from "~/components/Icons";
import MenuItem from "~/components/Menu/MenuItem";
import UserMenu from "~/components/Menu/UserMenu";
import { Menu, MenuItems } from "~/components/Menu/styles";
import { Container } from "~/components/Main/styles";
import { useRouter } from "next/router";

// Motion
import { AnimatePresence, motion } from "framer-motion";

export interface IMenuItem {
  title: string;
  icon: JSX.Element;
  link: string;
}

export interface DefaultProps {
  children: React.ReactNode;
}

export default function Default(props: DefaultProps) {
  const router = useRouter();

  const menuItems: IMenuItem[] = [
    {
      title: "Home",
      icon: <IconHome />,
      link: "/home",
    },
    {
      title: "Pontuar",
      icon: <IconPlus />,
      link: "/points/create",
    },
    {
      title: "Regras",
      icon: <IconPaper />,
      link: "/rules",
    },
  ];

  return (
    <div className={styles.bg}>
      <Head>
        <title>CMS • Diamond</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu>
          <Image
            className={styles.logo}
            src={"/images/logo.svg"}
            alt="Logo"
            width={32}
            height={32}
            draggable={false}
          />

          <MenuItems>
            {menuItems.map((item: IMenuItem) => (
              <MenuItem
                key={item.link}
                icon={item.icon}
                title={item.title}
                link={item.link}
                isActive={router.pathname == item.link}
              />
            ))}
          </MenuItems>

          <UserMenu />
        </Menu>

        <Container>
          <AnimatePresence>
            <motion.section
              key={router.pathname}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
            >
              {props.children}
            </motion.section>
          </AnimatePresence>
        </Container>
      </main>
    </div>
  );
}
